WAZO-2386: export events
wazo-platform/wazo-call-logd pull request #128
Opened 2021-07-15 14:16 UTC by bloom1

2021-07-15 15:00 UTC, bloom1 commented
recheck

2021-07-16 14:58 UTC, pc-m requested changes

2021-07-16 14:58 UTC, pc-m commented on wazo_call_logd/plugins/cdr/celery_tasks.py
> +        bus_publisher.flush_and_stop()
The thread should be stopped when an exception occurs

2021-07-16 15:39 UTC, pc-m approved these changes

2021-07-16 17:12 UTC, pc-m approved these changes

2021-07-16 17:49 UTC, merged