added debug flag to wazo-call-logs cli
wazo-platform/wazo-call-logd pull request #210
Opened 2023-12-14 14:27 UTC by DrPyser

Added `--debug` flag to `wazo-call-logs` cli.

2023-12-14 14:52 UTC, sduthil requested changes

2023-12-14 14:52 UTC, sduthil commented on wazo_call_logd/main_sweep.py
> +        logging.root.setLevel(logging.DEBUG)
You should change the call to `setup_logging` above instead.

2023-12-14 14:52 UTC, sduthil commented on wazo_call_logd/main_sweep.py
> +        '-d', '--debug', action='store_true', dest='debug', help='Enable debug logging'
`-d` is already taken by the previous option

2023-12-20 17:41 UTC, jfbourque commented
recheck

2024-01-02 17:35 UTC, sduthil approved these changes

2024-01-02 17:49 UTC, merged